default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: "123123"
  host: 127.0.0.1

development:
  <<: *default
  database: datn

test:
  <<: *default
  database: datn_test

production:
  <<: *default
  database: datn_production
